<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>TacoStationMonitor</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Images\Odin-Workstation-Console-Logo_icon--32px-gray-scale.png" />
    <None Remove="Images\Odin-Workstation-Logo_white-text-55px.png" />
    <None Remove="Images\OwsLogo_icon.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.3" />

    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />

    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.158" />

    <PackageReference Include="Serilog" Version="4.4.0" />

    <PackageReference Include="Serilog.Extensions.Logging" Version="8.0.0" />

    <PackageReference Include="Serilog.Sinks.Seq" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\app-odinStationMonitor-Library\app-odinStationMonitor-Library.csproj" />
    <ProjectReference Include="..\app-odinstationMonitor-LIC\app-odinstationMonitor-LIC.csproj" />
    <ProjectReference Include="..\app-odinStationMonitor-Messaging\app-odinStationMonitor-Messaging.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <Generator></Generator>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\" />
    <Folder Include="Controls\" />
    <Folder Include="Views\" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\Odin-Workstation-Console-Logo_icon--32px-gray-scale.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Odin-Workstation-Logo_white-text-55px.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\OwsLogo_icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
